#include "AC_CustomControl_config.h"

#if AP_CUSTOMCONTROL_FYP_ENABLED

#include "AC_CustomControl_FYP.h"

#include <GCS_MAVLink/GCS.h>
#include <AP_Math/AP_Math.h>

// table of user settable parameters
const AP_Param::GroupInfo AC_CustomControl_FYP::var_info[] = {
    // @Param: ANG_P_PIT
    // @DisplayName: FYP Pitch Angle P Gain
    // @Description: Outer-loop proportional gain for pitch angle error
    // @User: Advanced
    AP_GROUPINFO("ANG_P_PIT", 1, AC_CustomControl_FYP, _kp_angle_pitch, 4.0f),

    // @Param: PIT_RMAX
    // @DisplayName: FYP Max Desired Pitch Rate
    // @Description: Maximum desired pitch rate generated by the outer loop in centidegrees/sec
    // @User: Advanced
    AP_GROUPINFO("PIT_RMAX", 2, AC_CustomControl_FYP, _pitch_rate_max_cdss, 20000.0f),

    // @Param: PIT_OMAX
    // @DisplayName: FYP Max Pitch Output
    // @Description: Maximum normalized pitch output sent by the custom controller
    // @User: Advanced
    AP_GROUPINFO("PIT_OMAX", 3, AC_CustomControl_FYP, _pitch_out_max, 0.5f),
    AP_GROUPINFO("RATE_P",    4, AC_CustomControl_FYP, _rate_p, 0.10f),
    AP_GROUPINFO("RATE_I",    5, AC_CustomControl_FYP, _rate_i, 0.01f),
    AP_GROUPINFO("RATE_D",    6, AC_CustomControl_FYP, _rate_d, 0.00f),
    AP_GROUPINFO("RATE_IMAX", 7, AC_CustomControl_FYP, _rate_imax, 0.30f),
    AP_GROUPEND
};

// initialize in the constructor
AC_CustomControl_FYP::AC_CustomControl_FYP(AC_CustomControl& frontend,
                                           AP_AHRS_View*& ahrs,
                                           AC_AttitudeControl*& att_control,
                                           AP_MotorsMulticopter*& motors,
                                           float dt) :
    AC_CustomControl_Backend(frontend, ahrs, att_control, motors, dt),
    _pid_rate_pitch_fyp(0.10f, 0.01f, 0.0f, 0.0f, 0.3f, 10.0f, 0.0f, 10.0f, dt)
{
    AP_Param::setup_object_defaults(this, var_info);
}

// update controller
// return roll, pitch, yaw controller output
Vector3f AC_CustomControl_FYP::update(void)

{
    // --- PITCH LOOP (top path) ---
    // Get current pitch and pitch rate from IMU (via AHRS)
    float current_pitch = _ahrs->pitch;
    float current_pitch_rate = _ahrs->get_gyro_latest().y;

    // Get desired pitch from main attitude target
    float desired_pitch = _atti_control->get_attitude_target_quat().get_euler_pitch();

    // P-controller: angle error → desired rate
    float desired_pitch_rate = _p_angle_pitch.get_p(desired_pitch - current_pitch);

    // PID: rate error → desired pitch acceleration
    float desired_pitch_acc = _pid_pitch_rate.update_all(
        desired_pitch_rate, current_pitch_rate, _dt);

    // --- POSITION/VELOCITY LOOP (bottom path) ---
    // Get position and velocity from AHRS/EKF
    Vector3f position, velocity;
    _ahrs->get_relative_position_NED_home(position);
    _ahrs->get_velocity_NED(velocity);

float desired_x_pos = 0.0f;  // or get from mission/GCS

    // PID: position error → desired velocity
    float desired_vel = _pid_position_x.update_all(
        desired_x_pos, position.x, _dt);

    // PID: velocity error → desired acceleration
    float desired_acc = _pid_velocity_x.update_all(
        desired_vel, velocity.x, _dt);

    // --- CONTROL ALLOCATION (physical calculations) ---
    // Map pitch_acc and x_acc to front thrust, rear thrust, tilt angle
    // This is the geometry-specific math for your frame:

float total_thrust = _motors->get_throttle();  // get from throttle controller
constexpr float K_pitch = 0.1f;
constexpr float MAX_PITCH_ACC = 10.0f;
    _front_thrust = total_thrust/2.0f + desired_pitch_acc * K_pitch;
    _rear_thrust  = total_thrust/2.0f - desired_pitch_acc * K_pitch;
    _tilt_angle   = asinf(desired_acc / total_thrust); // simplified

    // --- MOTOR MIXER OUTPUT ---
    // set_pitch sends the pitch demand to the motors library mixer
    _motors->set_pitch(desired_pitch_acc / MAX_PITCH_ACC);
    _motors->set_throttle(total_thrust);

    // Servo output for tilt angle via SRV_Channels
    SRV_Channels::set_output_scaled(SRV_Channel::k_motor_tilt, 
        _tilt_angle * TILT_SCALE);

    return Vector3f(0, desired_pitch_acc / MAX_PITCH_ACC, 0); // roll, pitch, yaw
}


// reset controller to avoid build up on the ground
// or to provide bumpless transfer from arducopter main controller
void AC_CustomControl_FYP::reset(void)
{
    _pid_rate_pitch_fyp.reset_filter();
    _pid_rate_pitch_fyp.reset_I();
}

#endif  // AP_CUSTOMCONTROL_FYP_ENABLED